services:
  app:
    container_name: rank-api
    image: rank-api:2.0.0
    restart: always
    env_file:
      - .env
    ports:
      - 8001:8000
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    command: [
      "uv", "run", "fastapi",
      "run", "app/main.py",
      "--port", "8000",
      "--workers", "1",
    ]
