"""init

Revision ID: 6955d3938c08
Revises:
Create Date: 2025-07-20 12:30:33.756256

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6955d3938c08"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "index",
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("index_id", sa.Integer(), nullable=False),
        sa.Column("subject_ids", postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.PrimaryKeyConstraint("season_id", "index_id"),
    )
    op.create_table(
        "subject",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("name_cn", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("images_grid", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("images_large", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("collection_total", sa.Integer(), nullable=True),
        sa.Column("average_comment", sa.Float(), nullable=True),
        sa.Column("drop_rate", sa.Float(), nullable=True),
        sa.Column("air_weekday", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("meta_tags", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subject")
    op.drop_table("index")
    # ### end Alembic commands ###
